#!/bin/sh

DATABASE='geosan'
USERNAME='aladoy'
HOSTNAME='localhost'

psql -h $HOSTNAME -U $USERNAME $DATABASE << EOF

COMMENT ON COLUMN syndemic.colaus_b.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_b.sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_b.datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_b.age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_b.brnsws IS 'Born in Switzerland';
COMMENT ON COLUMN syndemic.colaus_b.datarrival IS 'Date of arrival in Switzerland';
COMMENT ON COLUMN syndemic.colaus_b.bthpl_dem IS 'Country of birth';
COMMENT ON COLUMN syndemic.colaus_b.ethori_self IS 'Self-reported ethnicity';
COMMENT ON COLUMN syndemic.colaus_b.lvplyr IS 'How many years did you live in Switzerland';
COMMENT ON COLUMN syndemic.colaus_b.edtyp3 IS 'Educational level (3 gr)';
COMMENT ON COLUMN syndemic.colaus_b.edtyp4 IS 'Educational level (4 gr)';
COMMENT ON COLUMN syndemic.colaus_b.job_curr8 IS 'Job type (4 cats)';
COMMENT ON COLUMN syndemic.colaus_b.mrtsts2 IS 'Marital status (2 cats)';
COMMENT ON COLUMN syndemic.colaus_b.cvdbase IS 'Baseline cardiovascular disease, reported';
COMMENT ON COLUMN syndemic.colaus_b.cvdbase_adj IS 'Baseline cardiovascular disease, adjudicated';
COMMENT ON COLUMN syndemic.colaus_b.conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_b.sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_b.hta IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_b.hctld IS 'Have you ever been told that you had high cholesterol';
COMMENT ON COLUMN syndemic.colaus_b.dbtld IS 'Have you ever been told that you had diabetes';
COMMENT ON COLUMN syndemic.colaus_b.diab IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_b.phyact IS 'Physical activity (min 20 min/week)';
COMMENT ON COLUMN syndemic.colaus_b.polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_b.f0gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_b.f0gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_b.f0gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_b.f0STs_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_b.f0STt_tot IS 'State-Trait Anxiety Inventory- trait (lifetime)';
COMMENT ON COLUMN syndemic.colaus_b.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_b.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_b.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_b.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_b.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_b.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_b.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_b.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_b.plz4_init IS 'Initial postal code';


COMMENT ON COLUMN syndemic.colaus_f1.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_f1.f1sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_f1.f1datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_f1.f1age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_f1.f1mrtsts2 IS 'Marital status (2 cats)';
COMMENT ON COLUMN syndemic.colaus_f1.f1job_curr8 IS 'Job type (4 cats)';
COMMENT ON COLUMN syndemic.colaus_f1.f1conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_f1.f1sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_f1.f1hta IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_f1.f1hctld IS 'Have you ever been told that you had high cholesterol';
COMMENT ON COLUMN syndemic.colaus_f1.f1dbtld IS 'Have you ever been told that you had diabetes';
COMMENT ON COLUMN syndemic.colaus_f1.f1diab IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f1.polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_f1.f1gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_f1.f1gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_f1.f1gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_f1.f1sts_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_f1.f1stt_tot IS 'State-Trait Anxiety Inventory- trait (lifetime)';
COMMENT ON COLUMN syndemic.colaus_f1.f1cvd IS 'Cardiovascular disease since 2009/last part';
COMMENT ON COLUMN syndemic.colaus_f1.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f1.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f1.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f1.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_f1.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f1.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f1.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_f1.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_f1.plz4_init IS 'Initial postal code';


COMMENT ON COLUMN syndemic.colaus_f2.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_f2.f2sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_f2.f2datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_f2.f2datquest IS 'Date of questionnaire (if done)';
COMMENT ON COLUMN syndemic.colaus_f2.f2age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_f2.f2mrtsts IS 'Current marital status';
COMMENT ON COLUMN syndemic.colaus_f2.f2mrtsts2 IS 'Marital status (2 cats)';
COMMENT ON COLUMN syndemic.colaus_f2.f2dmst IS 'Current domestic situation';
COMMENT ON COLUMN syndemic.colaus_f2.f2nochd IS 'How many children do you have?';
COMMENT ON COLUMN syndemic.colaus_f2.f2sclhlp1 IS 'Are you receiving retirement social benefits (AVS)?';
COMMENT ON COLUMN syndemic.colaus_f2.f2sclhlp2 IS 'Are you receiving invalidity social benefits (AI)?';
COMMENT ON COLUMN syndemic.colaus_f2.f2job_curr1 IS 'Are you currently engaged in a professional activity?';
COMMENT ON COLUMN syndemic.colaus_f2.f2job_curr4 IS 'Current professional situation (work time)';
COMMENT ON COLUMN syndemic.colaus_f2.f2job_curr7 IS 'Current occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f2.f2job_not1 IS 'Reasons for not working';
COMMENT ON COLUMN syndemic.colaus_f2.f2job_prev4 IS 'Last known occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f2.f2family18 IS 'Household highest occupation (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f2.f2income1 IS 'Monthly household gross income';
COMMENT ON COLUMN syndemic.colaus_f2.f2income2 IS 'Monthly household gross income (Tertiles)';
COMMENT ON COLUMN syndemic.colaus_f2.f2income3 IS 'Nb. of persons <15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f2.f2income4 IS 'Nb. of persons >=15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f2.f2income5 IS 'Real financial difficulties to meet needs';
COMMENT ON COLUMN syndemic.colaus_f2.f2income6 IS 'Renouncing to health care due to financial difficulties';
COMMENT ON COLUMN syndemic.colaus_f2.f2Quest1 IS 'How would you rate your health?';
COMMENT ON COLUMN syndemic.colaus_f2.f2conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_f2.f2alcool2 IS 'Alcohol consumption (4 groups)';
COMMENT ON COLUMN syndemic.colaus_f2.f2sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_f2.f2equiv IS 'Cigarette equivalents';
COMMENT ON COLUMN syndemic.colaus_f2.f2hypdr IS 'Did a doctor tell you that you were hypertensive (since CoLaus 2)?';
COMMENT ON COLUMN syndemic.colaus_f2.f2crbpmed IS 'Do you take medication for high blood pressure?';
COMMENT ON COLUMN syndemic.colaus_f2.f2hta IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_f2.f2hctld IS 'Did a doctor tell you that you had high cholesterol (since CoLaus 2)?';
COMMENT ON COLUMN syndemic.colaus_f2.f2hypolip IS 'Hypolipidemic drug treatment (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f2.f2dbtld IS 'Have you ever been told that you have diabetes?';
COMMENT ON COLUMN syndemic.colaus_f2.f2diab IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f2.f2orldrg IS 'Oral antidiabetic drugs (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f2.f2insn IS 'Insulin (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f2.f2antidiab IS 'Antidiabetic drug treatment (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f2.f2care1 IS 'Nb of consultations/visits last 12 months';
COMMENT ON COLUMN syndemic.colaus_f2.f2care1b IS 'Nb of emergency consultations last 12 months';
COMMENT ON COLUMN syndemic.colaus_f2.f2care2 IS 'Nb of hospitalizations last 12 months';
COMMENT ON COLUMN syndemic.colaus_f2.f2seden IS 'Sedentary: yes 10% or less etj in 4+BMR, no more than 10% 4+BMR';
COMMENT ON COLUMN syndemic.colaus_f2.f2bmi IS 'Body mass index';
COMMENT ON COLUMN syndemic.colaus_f2.f2bmi_cat2 IS 'BMI categories (+ underw)';
COMMENT ON COLUMN syndemic.colaus_f2.f2waist_cat IS 'Abdominal obesity (WHO)';
COMMENT ON COLUMN syndemic.colaus_f2.f2na IS 'Sodium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f2.f2k IS 'Potassium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f2.f2cr IS 'Creatinin (micromol/L)';
COMMENT ON COLUMN syndemic.colaus_f2.polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_f2.f2gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_f2.f2gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_f2.f2gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_f2.f2sts_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_f2.f2stt_tot IS 'State-Trait Anxiety Inventory- trait (lifetime)';
COMMENT ON COLUMN syndemic.colaus_f2.f2cvd IS 'Cardiovascular disease since 2009/last part';
COMMENT ON COLUMN syndemic.colaus_f2.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f2.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f2.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f2.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_f2.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f2.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f2.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_f2.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_f2.plz4_init IS 'Initial postal code';


COMMENT ON COLUMN syndemic.colaus_f3.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_f3.f3sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_f3.f3datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_f3.f3datquest IS 'Date of questionnaire (if done)';
COMMENT ON COLUMN syndemic.colaus_f3.f3age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_f3.f3mrtsts IS 'Current marital status';
COMMENT ON COLUMN syndemic.colaus_f3.f3mrtsts2 IS 'Marital status (2 cats)';
COMMENT ON COLUMN syndemic.colaus_f3.f3dmst IS 'Current domestic situation';
COMMENT ON COLUMN syndemic.colaus_f3.f3nochd IS 'How many children do you have?';
COMMENT ON COLUMN syndemic.colaus_f3.f3sclhlp3 IS 'Do you live out of your professional activity?';
COMMENT ON COLUMN syndemic.colaus_f3.f3job_curr1 IS 'Are you currently engaged in a professional activity? (yes/no)';
COMMENT ON COLUMN syndemic.colaus_f3.f3job_curr4 IS 'Current professional situation (work time)';
COMMENT ON COLUMN syndemic.colaus_f3.f3job_curr7 IS 'Current occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f3.f3job_not2 IS 'Sick leave the last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.f3job_prev3 IS 'Last occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f3.f3income3 IS 'Nb. of persons <15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f3.f3income4 IS 'Nb. of persons >=15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f3.f3income5 IS 'Real financial difficulties to meet needs';
COMMENT ON COLUMN syndemic.colaus_f3.f3income6 IS 'Renouncing to health care due to financial difficulties';
COMMENT ON COLUMN syndemic.colaus_f3.f3assur1 IS 'Type of health insurance';
COMMENT ON COLUMN syndemic.colaus_f3.f3quest1 IS 'How would you rate your health?';
COMMENT ON COLUMN syndemic.colaus_f3.f3conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_f3.f3alcool2 IS 'Alcohol consumption (4 groups)';
COMMENT ON COLUMN syndemic.colaus_f3.f3sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_f3.f3equiv IS 'Cigarette equivalents';
COMMENT ON COLUMN syndemic.colaus_f3.f3hypdr IS 'Did a doctor tell you that you were hypertensive (since CoLaus 3)?';
COMMENT ON COLUMN syndemic.colaus_f3.f3crbpmed IS 'Do you take medication for high blood pressure?';
COMMENT ON COLUMN syndemic.colaus_f3.f3hta IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_f3.f3hctld IS 'Did a doctor tell you that you had high cholesterol (since CoLaus 3)?';
COMMENT ON COLUMN syndemic.colaus_f3.f3dbtld IS 'Have you ever been told that you have diabetes?';
COMMENT ON COLUMN syndemic.colaus_f3.f3diab IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f3.f3care1 IS 'Did you consult a doctor the last 12 months?';
COMMENT ON COLUMN syndemic.colaus_f3.f3care1a IS 'Nb of visits, family doctor, last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.f3care1b IS 'Nb of visits, specialist, last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.f3care3 IS 'Were you hospitalized at least 1 night, last 12 months?';
COMMENT ON COLUMN syndemic.colaus_f3.f3care3a IS 'Nb of hospital nights';
COMMENT ON COLUMN syndemic.colaus_f3.f3care4 IS 'Hospital emergency, last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.f3care4a IS 'Nb of hospital emergencies';
COMMENT ON COLUMN syndemic.colaus_f3.f3ipaq_excl IS 'Reasons for exclusion, IPAQ';
COMMENT ON COLUMN syndemic.colaus_f3.f3ipaq_score IS 'IPAQ scores';
COMMENT ON COLUMN syndemic.colaus_f3.f3ipaq_met_tot IS 'Total MET-min/week';
COMMENT ON COLUMN syndemic.colaus_f3.f3bmi IS 'Body mass index';
COMMENT ON COLUMN syndemic.colaus_f3.f3bmi_cat2 IS 'BMI categories (+ underw)';
COMMENT ON COLUMN syndemic.colaus_f3.f3waist_cat IS 'Abdominal obesity (WHO)';
COMMENT ON COLUMN syndemic.colaus_f3.f3na IS 'Sodium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f3.f3k IS 'Potassium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f3.f3cr IS 'Creatinin (micromol/L)';
COMMENT ON COLUMN syndemic.colaus_f3.polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_f3.f3gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_f3.f3gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_f3.f3gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_f3.f3sts_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_f3.f3stt_tot IS 'State-Trait Anxiety Inventory- trait (lifetime)';
COMMENT ON COLUMN syndemic.colaus_f3.f3cvd IS 'Cardiovascular disease since 2009/last part';
COMMENT ON COLUMN syndemic.colaus_f3.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f3.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f3.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f3.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_f3.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f3.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f3.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_f3.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_f3.plz4_init IS 'Initial postal code';

EOF
