#!/bin/sh

DATABASE='geosan'
USERNAME='aladoy'
HOSTNAME='localhost'

psql -h $HOSTNAME -U $USERNAME $DATABASE << EOF

COMMENT ON COLUMN syndemic.colaus_b.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_b.sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_b.datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_b.age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_b.brnsws IS 'Born in Switzerland';
COMMENT ON COLUMN syndemic.colaus_b.datarrival IS 'Date of arrival in Switzerland';
COMMENT ON COLUMN syndemic.colaus_b.bthpl_dem IS 'Country of birth';
COMMENT ON COLUMN syndemic.colaus_b.ethori_self IS 'Self-reported ethnicity';
COMMENT ON COLUMN syndemic.colaus_b.lvplyr IS 'How many years did you live in Switzerland';
COMMENT ON COLUMN syndemic.colaus_b.edtyp3 IS 'Educational level (3 gr)';
COMMENT ON COLUMN syndemic.colaus_b.edtyp4 IS 'Educational level (4 gr)';
COMMENT ON COLUMN syndemic.colaus_b.job_curr8 IS 'Job type (4 cats)';
COMMENT ON COLUMN syndemic.colaus_b.cvdbase IS 'Baseline cardiovascular disease, reported';
COMMENT ON COLUMN syndemic.colaus_b.cvdbase_adj IS 'Baseline cardiovascular disease, adjudicated';
COMMENT ON COLUMN syndemic.colaus_b.conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_b.sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_b.HTA IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_b.hctld IS 'Have you ever been told that you had high cholesterol';
COMMENT ON COLUMN syndemic.colaus_b.dbtld IS 'Have you ever been told that you had diabetes';
COMMENT ON COLUMN syndemic.colaus_b.DIAB IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_b.phyact IS 'Physical activity (min 20 min/week)';
COMMENT ON COLUMN syndemic.colaus_b.Polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_b.F0gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_b.F0gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_b.F0gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_b.F0STs_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_b.F0STt_tot IS 'State-Trait Anxiety Inventory- trait (lifetime)';
COMMENT ON COLUMN syndemic.colaus_b.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_b.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_b.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_b.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_b.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_b.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_b.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_b.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_b.plz4_init IS 'Initial postal code';


COMMENT ON COLUMN syndemic.colaus_f1.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_f1.F1sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_f1.F1datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_f1.F1age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_f1.F1mrtsts2 IS 'Marital status (2 cats)';
COMMENT ON COLUMN syndemic.colaus_f1.F1job_curr8 IS 'Job type (4 cats)';
COMMENT ON COLUMN syndemic.colaus_f1.F1conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_f1.F1sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_f1.F1HTA IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_f1.F1hctld IS 'Have you ever been told that you had high cholesterol';
COMMENT ON COLUMN syndemic.colaus_f1.F1dbtld IS 'Have you ever been told that you had diabetes';
COMMENT ON COLUMN syndemic.colaus_f1.F1DIAB IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f1.Polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_f1.F1gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_f1.F1gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_f1.F1gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_f1.F1STs_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_f1.F1STt_tot IS 'State-Trait Anxiety Inventory- trait (lifetime)';
COMMENT ON COLUMN syndemic.colaus_f1.F1CVD IS 'Cardiovascular disease since 2009/last part';
COMMENT ON COLUMN syndemic.colaus_f1.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f1.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f1.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f1.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_f1.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f1.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f1.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_f1.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_f1.plz4_init IS 'Initial postal code';


COMMENT ON COLUMN syndemic.colaus_f2.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_f2.F2sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_f2.F2datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_f2.F2datquest IS 'Date of questionnaire (if done)';
COMMENT ON COLUMN syndemic.colaus_f2.F2age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_f2.F2mrtsts IS 'Current marital status';
COMMENT ON COLUMN syndemic.colaus_f2.F2mrtsts2 IS 'Marital status (2 cats)';
COMMENT ON COLUMN syndemic.colaus_f2.F2dmst IS 'Current domestic situation';
COMMENT ON COLUMN syndemic.colaus_f2.F2nochd IS 'How many children do you have?';
COMMENT ON COLUMN syndemic.colaus_f2.F2sclhlp1 IS 'Are you receiving retirement social benefits (AVS)?';
COMMENT ON COLUMN syndemic.colaus_f2.F2sclhlp2 IS 'Are you receiving invalidity social benefits (AI)?';
COMMENT ON COLUMN syndemic.colaus_f2.F2job_curr1 IS 'Are you currently engaged in a professional activity?';
COMMENT ON COLUMN syndemic.colaus_f2.F2job_curr4 IS 'Current professional situation (work time)';
COMMENT ON COLUMN syndemic.colaus_f2.F2job_curr7 IS 'Current occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f2.F2job_not1 IS 'Reasons for not working';
COMMENT ON COLUMN syndemic.colaus_f2.F2job_prev4 IS 'Last known occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f2.F2family18 IS 'Household highest occupation (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f2.F2income1 IS 'Monthly household gross income';
COMMENT ON COLUMN syndemic.colaus_f2.F2income2 IS 'Monthly household gross income (Tertiles)';
COMMENT ON COLUMN syndemic.colaus_f2.F2income3 IS 'Nb. of persons <15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f2.F2income4 IS 'Nb. of persons >=15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f2.F2income5 IS 'Real financial difficulties to meet needs';
COMMENT ON COLUMN syndemic.colaus_f2.F2income6 IS 'Renouncing to health care due to financial difficulties';
COMMENT ON COLUMN syndemic.colaus_f2.F2Quest1 IS 'How would you rate your health?';
COMMENT ON COLUMN syndemic.colaus_f2.F2conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_f2.F2alcool2 IS 'Alcohol consumption (4 groups)';
COMMENT ON COLUMN syndemic.colaus_f2.F2sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_f2.F2equiv IS 'Cigarette equivalents';
COMMENT ON COLUMN syndemic.colaus_f2.F2hypdr IS 'Did a doctor tell you that you were hypertensive (since CoLaus 2)?';
COMMENT ON COLUMN syndemic.colaus_f2.F2crbpmed IS 'Do you take medication for high blood pressure?';
COMMENT ON COLUMN syndemic.colaus_f2.F2HTA IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_f2.F2hctld IS 'Did a doctor tell you that you had high cholesterol (since CoLaus 2)?';
COMMENT ON COLUMN syndemic.colaus_f2.F2dbtld IS 'Have you ever been told that you have diabetes?';
COMMENT ON COLUMN syndemic.colaus_f2.F2DIAB IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f2.F2care1 IS 'Nb of consultations/visits last 12 months';
COMMENT ON COLUMN syndemic.colaus_f2.F2care1b IS 'Nb of emergency consultations last 12 months';
COMMENT ON COLUMN syndemic.colaus_f2.F2care2 IS 'Nb of hospitalizations last 12 months';
COMMENT ON COLUMN syndemic.colaus_f2.F2seden IS 'Sedentary: yes 10% or less etj in 4+BMR, no more than 10% 4+BMR';
COMMENT ON COLUMN syndemic.colaus_f2.F2BMI IS 'Body mass index';
COMMENT ON COLUMN syndemic.colaus_f2.F2BMI_cat2 IS 'BMI categories (+ underw)';
COMMENT ON COLUMN syndemic.colaus_f2.F2waist_cat IS 'Abdominal obesity (WHO)';
COMMENT ON COLUMN syndemic.colaus_f2.F2na IS 'Sodium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f2.F2k IS 'Potassium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f2.F2cr IS 'Creatinin (micromol/L)';
COMMENT ON COLUMN syndemic.colaus_f2.Polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_f2.F2gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_f2.F2gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_f2.F2gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_f2.F2STs_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_f2.F2STt_tot IS 'State-Trait Anxiety Inventory- trait (lifetime)';
COMMENT ON COLUMN syndemic.colaus_f2.F2CVD IS 'Cardiovascular disease since 2009/last part';
COMMENT ON COLUMN syndemic.colaus_f2.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f2.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f2.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f2.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_f2.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f2.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f2.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_f2.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_f2.plz4_init IS 'Initial postal code';


COMMENT ON COLUMN syndemic.colaus_f3.pt IS 'CoLaus ID';
COMMENT ON COLUMN syndemic.colaus_f3.F3sex IS 'Sex, numeric, 1=male, 0=female';
COMMENT ON COLUMN syndemic.colaus_f3.F3datexam IS 'Date of physical examination (if done)';
COMMENT ON COLUMN syndemic.colaus_f3.F3datquest IS 'Date of questionnaire (if done)';
COMMENT ON COLUMN syndemic.colaus_f3.F3age IS 'Age (years)';
COMMENT ON COLUMN syndemic.colaus_f3.F3mrtsts IS 'Current marital status';
COMMENT ON COLUMN syndemic.colaus_f3.F3mrtsts2 IS 'Marital status (2 cats)';
COMMENT ON COLUMN syndemic.colaus_f3.F3dmst IS 'Current domestic situation';
COMMENT ON COLUMN syndemic.colaus_f3.F3nochd IS 'How many children do you have?';
COMMENT ON COLUMN syndemic.colaus_f3.F3sclhlp3 IS 'Do you live out of your professional activity?';
COMMENT ON COLUMN syndemic.colaus_f3.F3job_curr1 IS 'Are you currently engaged in a professional activity? (yes/no)';
COMMENT ON COLUMN syndemic.colaus_f3.F3job_curr4 IS 'Current professional situation (work time)';
COMMENT ON COLUMN syndemic.colaus_f3.F3job_curr7 IS 'Current occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f3.F3job_not2 IS 'Sick leave the last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.F3job_prev3 IS 'Last occupational position (ESEC)';
COMMENT ON COLUMN syndemic.colaus_f3.F3income3 IS 'Nb. of persons <15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f3.F3income4 IS 'Nb. of persons >=15y in the household depending on income';
COMMENT ON COLUMN syndemic.colaus_f3.F3income5 IS 'Real financial difficulties to meet needs';
COMMENT ON COLUMN syndemic.colaus_f3.F3income6 IS 'Renouncing to health care due to financial difficulties';
COMMENT ON COLUMN syndemic.colaus_f3.F3assur1 IS 'Type of health insurance';
COMMENT ON COLUMN syndemic.colaus_f3.F3Quest1 IS 'How would you rate your health?';
COMMENT ON COLUMN syndemic.colaus_f3.F3conso_hebdo IS 'Weekly alcohol consumption (units)';
COMMENT ON COLUMN syndemic.colaus_f3.F3alcool2 IS 'Alcohol consumption (4 groups)';
COMMENT ON COLUMN syndemic.colaus_f3.F3sbsmk IS 'Smoking status';
COMMENT ON COLUMN syndemic.colaus_f3.F3equiv IS 'Cigarette equivalents';
COMMENT ON COLUMN syndemic.colaus_f3.F3hypdr IS 'Did a doctor tell you that you were hypertensive (since CoLaus 3)?';
COMMENT ON COLUMN syndemic.colaus_f3.F3crbpmed IS 'Do you take medication for high blood pressure?';
COMMENT ON COLUMN syndemic.colaus_f3.F3HTA IS 'Hypertension (>=140/90 or ttt)';
COMMENT ON COLUMN syndemic.colaus_f3.F3hctld IS 'Did a doctor tell you that you had high cholesterol (since CoLaus 3)?';
COMMENT ON COLUMN syndemic.colaus_f3.F3dbtld IS 'Have you ever been told that you have diabetes?';
COMMENT ON COLUMN syndemic.colaus_f3.F3DIAB IS 'Diabetes using FPG>=7.0 mmol/L (Y/N)';
COMMENT ON COLUMN syndemic.colaus_f3.F3care1 IS 'Did you consult a doctor the last 12 months?';
COMMENT ON COLUMN syndemic.colaus_f3.F3care1a IS 'Nb of visits, family doctor, last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.F3care1b IS 'Nb of visits, specialist, last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.F3care3 IS 'Were you hospitalized at least 1 night, last 12 months?';
COMMENT ON COLUMN syndemic.colaus_f3.F3care3a IS 'Nb of hospital nights';
COMMENT ON COLUMN syndemic.colaus_f3.F3care4 IS 'Hospital emergency, last 12 months';
COMMENT ON COLUMN syndemic.colaus_f3.F3care4a IS 'Nb of hospital emergencies';
COMMENT ON COLUMN syndemic.colaus_f3.F3IPAQ_excl IS 'Reasons for exclusion, IPAQ';
COMMENT ON COLUMN syndemic.colaus_f3.F3IPAQ_score IS 'IPAQ scores';
COMMENT ON COLUMN syndemic.colaus_f3.F3IPAQ_MET_tot IS 'Total MET-min/week';
COMMENT ON COLUMN syndemic.colaus_f3.F3BMI IS 'Body mass index';
COMMENT ON COLUMN syndemic.colaus_f3.F3BMI_cat2 IS 'BMI categories (+ underw)';
COMMENT ON COLUMN syndemic.colaus_f3.F3waist_cat IS 'Abdominal obesity (WHO)';
COMMENT ON COLUMN syndemic.colaus_f3.F3na IS 'Sodium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f3.F3k IS 'Potassium (mmol/L)';
COMMENT ON COLUMN syndemic.colaus_f3.F3cr IS 'Creatinin (micromol/L)';
COMMENT ON COLUMN syndemic.colaus_f3.Polypharm IS 'Polypharmacy (5 or more daily medications)';
COMMENT ON COLUMN syndemic.colaus_f3.F3gaf_l IS 'Global Assessment of Functioning - lifetime';
COMMENT ON COLUMN syndemic.colaus_f3.F3gaf_w IS 'Global Assessment of Functioning - worst';
COMMENT ON COLUMN syndemic.colaus_f3.F3gaf_c IS 'Global Assessment of Functioning - current';
COMMENT ON COLUMN syndemic.colaus_f3.F3STs_tot IS 'State-Trait Anxiety Inventory- state (current)';
COMMENT ON COLUMN syndemic.colaus_f3.F3CVD IS 'Cardiovascular disease since 2009/last part';
COMMENT ON COLUMN syndemic.colaus_f3.strname IS 'Street name used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f3.deinr IS 'Street number used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f3.plz4 IS 'Postal code used for geocoding';
COMMENT ON COLUMN syndemic.colaus_f3.municipality IS 'Municipality';
COMMENT ON COLUMN syndemic.colaus_f3.coordx_21781 IS 'X-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f3.coordy_21781 IS 'Y-coord (EPSG:21781). Geocoded by M.Vieira.';
COMMENT ON COLUMN syndemic.colaus_f3.strname_init IS 'Initial street name';
COMMENT ON COLUMN syndemic.colaus_f3.deinr_init IS 'Initial street number';
COMMENT ON COLUMN syndemic.colaus_f3.plz4_init IS 'Initial postal code';

EOF
